[package]
name = "ton-kafka-producer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
argh = "0.1"
async-trait = "0.1"
atty = "0.2.14"
base64 = "0.13"
broxus-util = { version = "0.1.4", features = ["config", "alloc", "alloc-profiling", "public-ip", "signal"] }
chrono = "0.4"
config = { version = "0.13", default-features = false, features = ["yaml"] }
countme = { version = "3.0.0", features = ["enable"] }

everscale-jrpc-server = { git = "https://github.com/broxus/everscale-jrpc.git", default-features = false }
everscale-network = "0.4.0"
futures-util = "0.3"
hex = "0.4"
indicatif = "0.17.0-rc.9"
once_cell = "1.10.0"
pomfrit = "0.1"
rand = "0.8"
rdkafka = { version = "0.29.0", features = ["ssl-vendored", "tokio"] }
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
tokio = { version = "1.17.0", features = ["full", "parking_lot"] }
ton-block-compressor = { git = "https://github.com/broxus/ton-block-compressor" }
ton-indexer = { git = "https://github.com/broxus/ton-indexer.git", features = ["count-cells", "archive-uploader"] }

# TON specific dependencies
ton_block = { git = "https://github.com/broxus/ton-labs-block" }
ton_block_json = { git = "https://github.com/broxus/ton-labs-block-json" }
ton_types = { git = "https://github.com/broxus/ton-labs-types" }

tracing = "0.1.34"
tracing-subscriber = { version = "0.3", features = ["registry", "fmt", "std", "env-filter", "json", "tracing-log"] }

[dev-dependencies]
cargo-husky = { version = "1", features = ["run-cargo-clippy", "run-cargo-fmt"] }

[features]
default = ["sasl"]
sasl = ["rdkafka/sasl"]

[profile.release]
debug = true
